name: Build MangaTR Solo
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Otomatik Kod Formatlayici (Spotless Fix)
        run: ./gradlew :src:tr:mangatr:spotlessApply

      - name: Build MangaTR APK
        run: ./gradlew :src:tr:mangatr:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mangatr-extension
          path: "**/*.apk"
